name: ðŸŒ Test Web
on:
  pull_request:
    paths:
      - ".github/workflows/build-web.yml"
      - "package.json"
      - "yarn.lock"
      - "FabricExample/**"
      - "src/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-web.yml"
      - "package.json"
      - "yarn.lock"
      - "FabricExample/**"
      - "src/**"

jobs:
  build-web:
    name: ðŸ—ï¸ Build web
    defaults:
      run:
        working-directory: FabricExample
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Get yarn cache directory path
        id: fabric-yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Restore node_modules from cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.fabric-yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-fabric-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-fabric-yarn-
      - name: Install node_modules for FabricExample/
        run: yarn install --frozen-lockfile
      - name: Install root dependencies
        run: yarn install --frozen-lockfile --cwd ..

      - name: Build web
        run: yarn build:web
