name: ðŸ¤– Build Android Fabric

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-android-fabric-windows.yml"
      - "android/**"
      - "FabricExample/android/**"
      - "yarn.lock"
      - "FabricExample/yarn.lock"
      - "FabricExample/patches/**"
      - "src/specs/**"
  pull_request:
    paths:
      - ".github/workflows/build-android-fabric-windows.yml"
      - "android/**"
      - "FabricExample/android/**"
      - "yarn.lock"
      - "FabricExample/yarn.lock"
      - "FabricExample/patches/**"
      - "src/specs/**"

jobs:
  build:
    name: ðŸ’  Build Android Fabric Example App
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Move to shorter path
        shell: pwsh
        run: |
          # First, change to the parent directory to avoid locking the directory
          cd D:\a

          # Move the entire project to a much shorter path
          # Original: D:\a\react-native-keyboard-controller\react-native-keyboard-controller
          # New: D:\project
          Move-Item "react-native-keyboard-controller\react-native-keyboard-controller" "D:\project"

          # Verify the move
          Write-Host "Contents of D:\project:"
          Get-ChildItem "D:\project" | ForEach-Object { Write-Host $_.Name }

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Get yarn cache directory path
        id: fabric-yarn-cache-dir-path
        shell: pwsh
        run: |
          cd D:\project
          $dir = yarn cache dir
          echo "dir=$dir" >> $env:GITHUB_OUTPUT

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.fabric-yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-fabric-yarn-${{ hashFiles('D:/project/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-fabric-yarn-

      - name: Install node_modules for FabricExample/
        shell: pwsh
        run: |
          cd D:\project\FabricExample
          yarn install --frozen-lockfile

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\.gradle\caches
            C:\Users\runneradmin\.gradle\wrapper
          key: ${{ runner.os }}-fabric-gradle-${{ hashFiles('D:/project/FabricExample/android/**/*.gradle*', 'D:/project/FabricExample/android/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-fabric-gradle-

      - name: Run Gradle Build for FabricExample/android/
        shell: pwsh
        run: |
          cd D:\project\FabricExample\android
          .\gradlew.bat assembleDebug --build-cache -PreactNativeArchitectures=arm64-v8a
