name: Build Android Fabric

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-android-fabric.yml'
      - 'android/**'
      - 'FabricExample/android/**'
      - 'yarn.lock'
      - 'FabricExample/yarn.lock'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/build-android-fabric.yml'
      - 'android/**'
      - 'FabricExample/android/**'
      - 'yarn.lock'
      - 'FabricExample/yarn.lock'
      - 'src/**'

jobs:
  build:
    name: Build Android Fabric Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Get yarn cache directory path
        id: fabric-yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.fabric-yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-fabric-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules
        run: yarn install --frozen-lockfile
      - name: Install node_modules for FabricExample/
        run: yarn install --frozen-lockfile --cwd FabricExample

      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/build
            android/.cxx
            FabricExample/android/build
            FabricExample/android/.cxx
            FabricExample/android/.gradle
            FabricExample/android/app/build
            FabricExample/android/app/.cxx
            FabricExample/node_modules/react-native/ReactAndroid/build
            FabricExample/node_modules/react-native/ReactAndroid/hermes-engine/build
            FabricExample/node_modules/react-native/ReactAndroid/hermes-engine/.cxx
          key: ${{ runner.os }}-fabric-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-fabric-gradle-
      - name: Run Gradle Build for android/
        run: cd android && ./gradlew assembleDebug --build-cache && cd ..
      - name: Run Gradle Build for FabricExample/android/
        run: cd FabricExample/android && ./gradlew assembleDebug --build-cache -PreactNativeArchitectures=arm64-v8a && cd ../..