name: ðŸ¤– Build Android Fabric

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-android-fabric-windows.yml"
      - "android/**"
      - "yarn.lock"
      - "src/specs/**"
      - "common/**"
  pull_request:
    paths:
      - ".github/workflows/build-android-fabric-windows.yml"
      - "android/**"
      - "yarn.lock"
      - "src/specs/**"
      - "common/**"

jobs:
  build:
    name: ðŸ’  Build Android on Windows
    runs-on: windows-latest

    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Create sample app
        run: npx @react-native-community/cli@latest init windows --version 0.83.1
      - name: Get yarn cache directory path
        id: fabric-windows-yarn-cache-dir-path
        shell: pwsh
        run: |
          $dir = yarn cache dir
          echo "dir=$dir" >> $env:GITHUB_OUTPUT
      - name: Restore node_modules from cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.fabric-windows-yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-fabric-windows-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-fabric-windows-yarn-
      - name: Install node_modules for windows/
        shell: pwsh
        run: |
          yarn install --frozen-lockfile --cwd windows
      - name: Link keyboard controller
        shell: pwsh
        run: yarn add react-native-keyboard-controller@link:../
      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\.gradle\caches
            C:\Users\runneradmin\.gradle\wrapper
          key: ${{ runner.os }}-fabric-windows-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-fabric-windows-gradle-
      - name: Run Gradle Build for windows/android/
        shell: pwsh
        run: |
          cd windows\android
          .\gradlew.bat assembleDebug --build-cache -PreactNativeArchitectures=arm64-v8a
