name: ğŸ‘¨â€ğŸ’» Verify JS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: ğŸ”€ Compile TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          cd example
          yarn install --frozen-lockfile
      - name: Run TypeScript
        run: yarn typescript
  lint:
    name: ğŸ” Lint TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Lint
        run: yarn lint
  tests:
    name: ğŸ“– Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          cd example
          yarn install --frozen-lockfile
          cd ../FabricExample
          yarn install --frozen-lockfile
      - name: Run lib tests
        run: yarn test src
      - name: Run example app tests (verify mocks)
        run: |
          cd example
          yarn test
      - name: Run example fabric app tests (verify mocks)
        run: |
          cd FabricExample
          yarn test
