name: ğŸ“± Validate Android

env:
  REACT_NATIVE_VERSION: 0.76.2

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/verify-android.yml"
      - "android/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/verify-android.yml"
      - "android/**"

jobs:
  ktlint:
    runs-on: ubuntu-latest
    name: ğŸ” Kotlin Lint
    steps:
      - uses: actions/checkout@v4
      - uses: touchlab-lab/ktlint-action-setup@1.0.0
        with:
          ktlint_version: 1.3.1
      - run: ktlint "android/src/**/*.kt"
  android-lint:
    runs-on: ubuntu-latest
    name: ğŸ” Android Lint
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Install dependencies
        run: yarn install --frozen-lockfile --cwd ..
      - name: Run Gradle Lint
        run: ./gradlew lint -PreactNativeVersion=${{ env.REACT_NATIVE_VERSION }}
  android-build:
    runs-on: ubuntu-latest
    name: ğŸ—ï¸ Android Build
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Install dependencies
        run: yarn install --frozen-lockfile --cwd ..
      - name: Run Gradle Assemble
        run: ./gradlew assembleDebug -PreactNativeVersion=${{ env.REACT_NATIVE_VERSION }}
  detekt:
    runs-on: ubuntu-latest
    name: ğŸ§¬ Run detekt
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Install Detekt
        run: |
          curl -sSLO https://github.com/detekt/detekt/releases/download/v1.23.1/detekt-cli-1.23.1.zip
          unzip detekt-cli-1.23.1.zip
      - name: Run Detekt
        run: ./detekt-cli-1.23.1/bin/detekt-cli
  unit-tests:
    name: ğŸ“– Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Install dependencies
        run: yarn install --frozen-lockfile --cwd ..
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest -PreactNativeVersion=${{ env.REACT_NATIVE_VERSION }}
